import assert from 'node:assert/strict';
import {test} from 'node:test';
import {rankSelectorCandidates,type SafeDomNode} from '../src/index.ts';
const node=(tag:string,attributes:Record<string,string>):SafeDomNode=>({tagName:tag,attributes});
test('ranks semantic, unique DOM attributes for a missing CSS selector',()=>{
 const results=rankSelectorCandidates({method:'querySelector',oldSelector:'#submit-btn',nodes:[node('BUTTON',{'data-testid':'submit-button',id:'submit-v2',class:'btn primary'}),node('BUTTON',{id:'cancel-button'}),node('DIV',{class:'btn'})]});
 assert.ok(results.length>0);
 assert.equal(results[0]?.expression,'[data-testid="submit-button"]');
 assert.equal(results[0]?.matchCount,1);
 assert.equal(results[0]?.source,'DOMSnapshot');
 assert.ok(results.every(x=>x.approved===false && x.validationLevel==='candidate-only'));
});
test('rejects duplicate selectors, personal data, and suspicious autogenerated keys',()=>{
 const results=rankSelectorCandidates({method:'querySelector',oldSelector:'.save',nodes:[
 node('BUTTON',{'data-testid':'same-button',class:'save'}),node('BUTTON',{'data-testid':'same-button',class:'save'}),
 node('INPUT',{id:'john@example.com',name:'1694589012'}),node('A',{id:'a234567890123456789abcdef0123456789012'})]});
 assert.ok(results.every(x=>!x.expression.includes('same-button')&&!x.expression.includes('john')&&!x.expression.includes('16945')));
 assert.equal(results.some(x=>x.matchCount!==1),false);
});
test('getElementById candidates emit raw id argument rather than CSS selector',()=>{
 const results=rankSelectorCandidates({method:'getElementById',oldSelector:'old-button',nodes:[node('BUTTON',{id:'new-button','data-testid':'save-button'})]});
 assert.deepEqual(results.map(x=>x.expression),['new-button']);
 assert.equal(results[0]?.cssSelector,'#new-button');
});
test('never suggests for runtime-bound or receiver-scoped calls',()=>{
 const nodes=[node('DIV',{id:'new-item'})];
 assert.deepEqual(rankSelectorCandidates({method:'closest',oldSelector:'.old',nodes}),[]);
 assert.deepEqual(rankSelectorCandidates({method:'querySelector',oldSelector:'div',nodes,runtimeRequired:true}),[]);
 assert.deepEqual(rankSelectorCandidates({method:'querySelectorAll',oldSelector:'.old',nodes}),[]);
});
test('candidate output is size-bounded and stable across repeated runs',()=>{
 const nodes=Array.from({length:300},(_,i)=>node('DIV',{id:"component-"+i}));
 const input={method:'querySelector',oldSelector:'#component-old',nodes};
 const a=rankSelectorCandidates(input);const b=rankSelectorCandidates(input);
 assert.deepEqual(a,b);assert.ok(a.length<=10);assert.ok(a.every(x=>x.expression.length<=160));
});
